apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: ["/bin/sh", "-c", "echo APP_NAME=$APP_NAME && echo APP_LANGUAGE=$APP_LANGUAGE && echo DB_USERNAME=$DB_USERNAME && echo DB_PASSWORD=$DB_PASSWORD"]
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: app_name
        - name: APP_LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: app_language
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
